In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [25]:
from scipy import spatial

In [72]:
import operator

In [19]:
file_path = 'train_noemo.csv'
file_encoding = 'utf8'        # set file_encoding to the file encoding (utf8, latin1, etc.)
input_fd = open(file_path, encoding=file_encoding, errors = 'ignore')

df = pd.read_csv(input_fd, header=None)

In [16]:
df.head()

,0,1,2,3,4,5
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [20]:
file_path = 'spotify-2023.csv'
file_encoding = 'utf8'        # set file_encoding to the file encoding (utf8, latin1, etc.)
input_fd_spotify = open(file_path, encoding=file_encoding, errors = 'ignore')

spotify_df = pd.read_csv(input_fd_spotify)

In [173]:
spotify_df

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

In [28]:
artists = spotify_df['artist(s)_name']
spotify_df['artists'] = spotify_df['artist(s)_name'].str.strip('[]').str.replace(' ','').str.replace("'",'')
spotify_df['artists'] = spotify_df['artists'].str.split(',')

str

In [29]:
spot = spotify_df.copy()
spot['artist(s)_name'] = spot['artist(s)_name'].str.strip('[]').str.replace(' ','').str.replace("'",'')
spot['artist(s)_name'] = spot['artist(s)_name'].str.split(',')

In [30]:
spot

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"[Latto, JungKook]",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,[MykeTowers],1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,[OliviaRodrigo],1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,[TaylorSwift],1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,[BadBunny],1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,[SelenaGomez],1,2022,11,3,953,0,91473363,61,...,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,[TaylorSwift],1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"[Feid, PauloLondra]",2,2022,11,3,573,0,73513683,2,...,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"[Feid, Sech, Jhayco]",3,2022,10,20,1320,0,133895612,29,...,97,C#,Major,82,67,77,8,0,12,5
952,Alone,[BurnaBoy],1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

In [42]:
low = 34
med = 67
high = 100
metrics = ['danceability_%', 'valence_%', 'energy_%']

In [45]:
df = spot.assign(danceability=pd.cut(spot['danceability_%'], 
                               bins=[0, 34, 67, 100], 
                               labels=['Low', 'Medium', 'High']))
df = df.assign(valence=pd.cut(spot['valence_%'], 
                               bins=[0, 34, 67, 100], 
                               labels=['Low', 'Medium', 'High']))
df = df.assign(energy=pd.cut(spot['energy_%'], 
                               bins=[0, 34, 67, 100], 
                               labels=['Low', 'Medium', 'High']))

In [ ]:
df

In [57]:
categories = ['Low', 'Medium', 'High']
def binary(cat):
    binaryList = []
    
    for x in categories:
        if x in cat:
            binaryList.append(1)
        else:
            binaryList.append(0)
    
    return binaryList

In [ ]:
df['danceability_bin'] = df['danceability'].apply(lambda x: binary(x))
df['valence_bin'] = df['valence'].apply(lambda x: binary(x))
df['energy_bin'] = df['energy'].apply(lambda x: binary(x))

In [59]:
artist_list = []
for index, row in spot.iterrows():
    artists = row["artist(s)_name"]
    
    for artist in artists:
        if artist not in artist_list:
            artist_list.append(artist)
len(artist_list)

699

In [61]:
def binary_art(artist):
    binaryList = []
    
    for x in artist_list:
        if x in artist:
            binaryList.append(1)
        else:
            binaryList.append(0)
    
    return binaryList

In [62]:
df['artist_bin'] = df['artist(s)_name'].apply(lambda x: binary_art(x))

In [64]:
df.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,instrumentalness_%,liveness_%,speechiness_%,danceability,valence,energy,danceability_bin,valence_bin,energy_bin,artist_bin
0,Seven (feat. Latto) (Explicit Ver.),"[Latto, JungKook]",2,2023,7,14,553,147,141381703,43,...,0,8,4,High,High,High,"[0, 0, 1]","[0, 0, 1]","[0, 0, 1]","[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,LALA,[MykeTowers],1,2023,3,23,1474,48,133716286,48,...,0,10,4,High,Medium,High,"[0, 0, 1]","[0, 1, 0]","[0, 0, 1]","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,vampire,[OliviaRodrigo],1,2023,6,30,1397,113,140003974,94,...,0,31,6,Medium,Low,Medium,"[0, 1, 0]","[1, 0, 0]","[0, 1, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,Cruel Summer,[TaylorSwift],1,2019,8,23,7858,100,800840817,116,...,0,11,15,Medium,Medium,High,"[0, 1, 0]","[0, 1, 0]","[0, 0, 1]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,WHERE SHE GOES,[BadBunny],1,2023,5,18,3133,50,303236322,84,...,63,11,6,Medium,Low,High,"[0, 1, 0]","[1, 0, 0]","[0, 0, 1]","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [92]:
df2 = df.copy()
df2.reset_index()

In [90]:
song_df = song_df.rename(columns={'index':'id'})

In [94]:
df2 = df2.reset_index()

In [97]:
df2 = df2.rename(columns={'index':'id'})
song_df = df2
song_df.head()

,id,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,...,instrumentalness_%,liveness_%,speechiness_%,danceability,valence,energy,danceability_bin,valence_bin,energy_bin,artist_bin
0,0,Seven (feat. Latto) (Explicit Ver.),"[Latto, JungKook]",2,2023,7,14,553,147,141381703,...,0,8,4,High,High,High,"[0, 0, 1]","[0, 0, 1]","[0, 0, 1]","[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,1,LALA,[MykeTowers],1,2023,3,23,1474,48,133716286,...,0,10,4,High,Medium,High,"[0, 0, 1]","[0, 1, 0]","[0, 0, 1]","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,2,vampire,[OliviaRodrigo],1,2023,6,30,1397,113,140003974,...,0,31,6,Medium,Low,Medium,"[0, 1, 0]","[1, 0, 0]","[0, 1, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,3,Cruel Summer,[TaylorSwift],1,2019,8,23,7858,100,800840817,...,0,11,15,Medium,Medium,High,"[0, 1, 0]","[0, 1, 0]","[0, 0, 1]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,4,WHERE SHE GOES,[BadBunny],1,2023,5,18,3133,50,303236322,...,63,11,6,Medium,Low,High,"[0, 1, 0]","[1, 0, 0]","[0, 0, 1]","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [99]:
q = song_df.iloc[2]
q['id']

2

In [115]:
for index, song in song_df.iloc[:5].iterrows():
    if song['id'] != q['id']:
        print('false')

false
false
false
false

In [122]:
def getNeighbors(query_song, K):
        distances = []
    
        for index, song in song_df.iterrows():
            if song['id'] != query_song['id']:
                dist = Similarity(query_song['id'], song['id'])
                distances.append((song['id'], song['track_name'], dist))
    
        distances.sort(key=operator.itemgetter(2))
        neighbors = []
    
        for x in range(K):
            neighbors.append(distances[x])
        return neighbors

In [145]:
for i in song_df.id.values:
    query_song = song_df.iloc[i]
    neighbors = getNeighbors(query_song, K=5)
    rec_titles = [neighbors[i][1] for i in range(len(neighbors))]
    song_df.loc[[i], 'recommendations'] = pd.Series([rec_titles], index=df.index[[i]])

In [146]:
song_df.head()

,id,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,...,liveness_%,speechiness_%,danceability,valence,energy,danceability_bin,valence_bin,energy_bin,artist_bin,recommendations
0,0,Seven (feat. Latto) (Explicit Ver.),"[Latto, JungKook]",2,2023,7,14,553,147,141381703,...,8,4,High,High,High,"[0, 0, 1]","[0, 0, 1]","[0, 0, 1]","[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",[I Can See You (Taylor���s Version) (From The ...
1,1,LALA,[MykeTowers],1,2023,3,23,1474,48,133716286,...,10,4,High,Medium,High,"[0, 0, 1]","[0, 1, 0]","[0, 0, 1]","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[PLAYA DEL INGL�, Super Shy, Flowers, Rush, Lo..."
2,2,vampire,[OliviaRodrigo],1,2023,6,30,1397,113,140003974,...,31,6,Medium,Low,Medium,"[0, 1, 0]","[1, 0, 0]","[0, 1, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[drivers license, deja vu, Daylight, Another L..."
3,3,Cruel Summer,[TaylorSwift],1,2019,8,23,7858,100,800840817,...,11,15,Medium,Medium,High,"[0, 1, 0]","[0, 1, 0]","[0, 0, 1]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Style, Mine (Taylor's Version), You Belong Wi..."
4,4,WHERE SHE GOES,[BadBunny],1,2023,5,18,3133,50,303236322,...,11,6,Medium,Low,High,"[0, 1, 0]","[1, 0, 0]","[0, 0, 1]","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Titi Me Pregunt, Tormenta (feat. Bad Bunny), ..."

In [147]:
song_df.to_csv('spotify_recs.csv')

In [123]:
nb = getNeighbors(song_df.iloc[2], 5)
print(nb)

[(535, 'drivers license', 0), (565, 'deja vu', 0), (13, 'Daylight', 1.0), (54, 'Another Love', 1.0), (65, 'Yellow', 1.0)]

In [141]:
nb[0][1]
rec_titles = [nb[i][1] for i in range(len(nb))]
rec_titles

['drivers license', 'deja vu', 'Daylight', 'Another Love', 'Yellow']

In [142]:
song_df['recommendations'] = np.nan
#song_df.loc[2, 'recommendations'] = nb
song_df.loc[[2], 'recommendations'] = pd.Series([rec_titles], index=df.index[[2]])

In [143]:
song_df.head()

,id,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,...,liveness_%,speechiness_%,danceability,valence,energy,danceability_bin,valence_bin,energy_bin,artist_bin,recommendations
0,0,Seven (feat. Latto) (Explicit Ver.),"[Latto, JungKook]",2,2023,7,14,553,147,141381703,...,8,4,High,High,High,"[0, 0, 1]","[0, 0, 1]","[0, 0, 1]","[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",NaN
1,1,LALA,[MykeTowers],1,2023,3,23,1474,48,133716286,...,10,4,High,Medium,High,"[0, 0, 1]","[0, 1, 0]","[0, 0, 1]","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",NaN
2,2,vampire,[OliviaRodrigo],1,2023,6,30,1397,113,140003974,...,31,6,Medium,Low,Medium,"[0, 1, 0]","[1, 0, 0]","[0, 1, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[drivers license, deja vu, Daylight, Another L..."
3,3,Cruel Summer,[TaylorSwift],1,2019,8,23,7858,100,800840817,...,11,15,Medium,Medium,High,"[0, 1, 0]","[0, 1, 0]","[0, 0, 1]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",NaN
4,4,WHERE SHE GOES,[BadBunny],1,2023,5,18,3133,50,303236322,...,11,6,Medium,Low,High,"[0, 1, 0]","[1, 0, 0]","[0, 0, 1]","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",NaN

In [124]:
song_df['recommendations'] = None
song_df.head()

,id,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,...,liveness_%,speechiness_%,danceability,valence,energy,danceability_bin,valence_bin,energy_bin,artist_bin,recommendations
0,0,Seven (feat. Latto) (Explicit Ver.),"[Latto, JungKook]",2,2023,7,14,553,147,141381703,...,8,4,High,High,High,"[0, 0, 1]","[0, 0, 1]","[0, 0, 1]","[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",None
1,1,LALA,[MykeTowers],1,2023,3,23,1474,48,133716286,...,10,4,High,Medium,High,"[0, 0, 1]","[0, 1, 0]","[0, 0, 1]","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",None
2,2,vampire,[OliviaRodrigo],1,2023,6,30,1397,113,140003974,...,31,6,Medium,Low,Medium,"[0, 1, 0]","[1, 0, 0]","[0, 1, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",None
3,3,Cruel Summer,[TaylorSwift],1,2019,8,23,7858,100,800840817,...,11,15,Medium,Medium,High,"[0, 1, 0]","[0, 1, 0]","[0, 0, 1]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",None
4,4,WHERE SHE GOES,[BadBunny],1,2023,5,18,3133,50,303236322,...,11,6,Medium,Low,High,"[0, 1, 0]","[1, 0, 0]","[0, 0, 1]","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",None

In [ ]:
k = 5
for song_id in song_df.id.values:
    neighbors = getNeighbors(song_id, k)

In [117]:
def Similarity(
    song1: int, 
    song2: int,
): # where song1 and song2 are the unique identifiers
    a = song_df.iloc[song1]
    b = song_df.iloc[song2]
    
    artistA = a['artist_bin']
    artistB = b['artist_bin']
    
    artistDistance = spatial.distance.cosine(artistA, artistB)
    
    danceA = a['danceability_bin']
    danceB = b['danceability_bin']
    danceDistance = spatial.distance.cosine(danceA, danceB)
    
    valenceA = a['valence_bin']
    valenceB = b['valence_bin']
    valenceDistance = spatial.distance.cosine(valenceA, valenceB)
    
    energyA = a['energy_bin']
    energyB = b['energy_bin']
    energyDistance = spatial.distance.cosine(energyA, energyB)
    
    return artistDistance + danceDistance + valenceDistance + energyDistance

- load data
- map song to k "nearest neighbors" via collaborative filtering (item-item)
- label dataset
- create dropdown in app
- select song and spit out top 3 more similar

## Get Suggestions

In [209]:
df.loc[df['track_name']=='Flowers']['artist(s)_name'].

id
12              Miley Cyrus
825    Lauren Spencer Smith
Name: artist(s)_name, dtype: object

In [207]:
list(set(df.loc[df['track_name']=='Flowers']['recommendations'].to_list()[0]))

[['LALA', 'Super Shy', 'Rush', 'Los del Espacio', 'Blank Space'],
 ['fukumean', "Creepin'", 'El Cielo', 'Unholy (feat. Kim Petras)', 'Ditto']]

In [ ]:
def get_suggestions(df, query)

## Functions to create plots

In [227]:
songs = list(set(song_df.track_name.values))
len(songs)

942

In [164]:
u, c = np.unique(songs, return_counts=True)
dup = u[c>1]
dup

array(['About Damn Time', 'Daylight', 'Die For You', 'Flowers',
       'Let It Snow! Let It Snow! Let It Snow!', 'Miss You', 'Numb',
       'SNAP', 'SPIT IN MY FACE!', 'Take My Breath', 'nan'], dtype='<U123')

In [171]:
song_df.loc[song_df['track_name']=='Cruel Summer']

,id,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,...,liveness_%,speechiness_%,danceability,valence,energy,danceability_bin,valence_bin,energy_bin,artist_bin,recommendations
3,3,Cruel Summer,[TaylorSwift],1,2019,8,23,7858,100,800840817,...,11,15,Medium,Medium,High,"[0, 1, 0]","[0, 1, 0]","[0, 0, 1]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Style, Mine (Taylor's Version), You Belong Wi..."

In [ ]:
df = song_df.copy()
df = df.set_index(['id'])
df.head()

In [175]:
df['artist(s)_name'] = spotify_df['artist(s)_name']
df.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,liveness_%,speechiness_%,danceability,valence,energy,danceability_bin,valence_bin,energy_bin,artist_bin,recommendations
id,,,,,,,,,,,,,,,,,,,,,
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,8,4,High,High,High,"[0, 0, 1]","[0, 0, 1]","[0, 0, 1]","[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",[I Can See You (Taylor���s Version) (From The ...
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,10,4,High,Medium,High,"[0, 0, 1]","[0, 1, 0]","[0, 0, 1]","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[PLAYA DEL INGL�, Super Shy, Flowers, Rush, Lo..."
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,31,6,Medium,Low,Medium,"[0, 1, 0]","[1, 0, 0]","[0, 1, 0]","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[drivers license, deja vu, Daylight, Another L..."
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,11,15,Medium,Medium,High,"[0, 1, 0]","[0, 1, 0]","[0, 0, 1]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Style, Mine (Taylor's Version), You Belong Wi..."
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,11,6,Medium,Low,High,"[0, 1, 0]","[1, 0, 0]","[0, 0, 1]","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Titi Me Pregunt, Tormenta (feat. Bad Bunny), ..."

In [194]:
df.to_csv('spotify_recs_2023_fixed.csv')

In [188]:
df = df.drop([574])

In [189]:
df.loc[df['streams'] == 'BPM110KeyAModeMajorDanceability53Valence75Energy69Acousticness7Instrumentalness0Liveness17Speechiness3']

Empty DataFrame
Columns: [track_name, artist(s)_name, artist_count, released_year, released_month, released_day, in_spotify_playlists, in_spotify_charts, streams, in_apple_playlists, in_apple_charts, in_deezer_playlists, in_deezer_charts, in_shazam_charts, bpm, key, mode, danceability_%, valence_%, energy_%, acousticness_%, instrumentalness_%, liveness_%, speechiness_%, danceability, valence, energy, danceability_bin, valence_bin, energy_bin, artist_bin, recommendations]
Index: []

[0 rows x 32 columns]

In [190]:
df['streams'] = df['streams'].apply(int)

In [162]:
len(song_df)

953

In [192]:
top_10 = df.groupby(['artist(s)_name']).sum()

In [180]:
top_10.columns.values

array(['artist_count', 'released_year', 'released_month', 'released_day',
       'in_spotify_playlists', 'in_spotify_charts', 'in_apple_playlists',
       'in_apple_charts', 'in_deezer_charts', 'bpm', 'danceability_%',
       'valence_%', 'energy_%', 'acousticness_%', 'instrumentalness_%',
       'liveness_%', 'speechiness_%'], dtype=object)

In [211]:
top_10 = top_10.sort_values('streams', ascending=False)[:10]
top_10

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
artist(s)_name,,,,,,,,,,,,,,,,,,
The Weeknd,22,44452,75,276,144053,180,14185552870,1677,1348,23,2634,1269,930,1406,453,31,433,173
Taylor Swift,34,68691,256,510,132974,542,14053658300,1796,1866,58,4268,2032,1209,1931,948,23,524,251
Ed Sheeran,9,18171,44,97,128758,94,13908947204,1448,488,43,1051,627,462,583,260,0,147,45
Harry Styles,17,34362,110,320,110026,185,11608645649,1741,545,76,2185,1043,918,1001,728,27,243,91
Bad Bunny,19,38414,90,170,51317,268,9997799607,589,852,56,2264,1428,1011,1268,434,63,345,187
Olivia Rodrigo,7,14149,31,116,47197,130,7442148916,710,429,15,1135,359,269,354,373,0,143,70
Eminem,4,8008,4,4,87331,152,6183805596,475,281,12,471,319,175,272,25,0,89,69
Bruno Mars,4,8044,35,15,32257,35,5846920599,87,0,0,544,248,183,243,152,0,62,17
Arctic Monkeys,4,8046,7,23,84016,190,5569806731,241,340,6,452,225,187,243,33,2,48,15
Imagine Dragons,3,6050,5,43,49878,80,5272484650,413,311,31,419,187,177,221,26,0,58,21

In [212]:
count, division = np.histogram(top_10['streams'])

In [222]:
ret = [(x, y) for x, y in zip(top_10.index.tolist(), top_10.streams.tolist())]

In [223]:
ret

[('The Weeknd', 14185552870),
 ('Taylor Swift', 14053658300),
 ('Ed Sheeran', 13908947204),
 ('Harry Styles', 11608645649),
 ('Bad Bunny', 9997799607),
 ('Olivia Rodrigo', 7442148916),
 ('Eminem', 6183805596),
 ('Bruno Mars', 5846920599),
 ('Arctic Monkeys', 5569806731),
 ('Imagine Dragons', 5272484650)]

In [220]:
top_10['streams'].values

array([14185552870, 14053658300, 13908947204, 11608645649,  9997799607,
        7442148916,  6183805596,  5846920599,  5569806731,  5272484650])

In [221]:
top_10.index.values

array(['The Weeknd', 'Taylor Swift', 'Ed Sheeran', 'Harry Styles',
       'Bad Bunny', 'Olivia Rodrigo', 'Eminem', 'Bruno Mars',
       'Arctic Monkeys', 'Imagine Dragons'], dtype=object)

In [196]:
max_streams = max(df.streams.values)

3703895074